apiVersion: apps/v1
kind: Deployment
metadata:
  name: comics-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: comics-server
  template:
    metadata:
      labels:
        app: comics-server
    spec:
      containers:
        - name: comics-server
          image: damianesteban/comics-server:latest
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: DATABASE_URL
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: comics-server
spec:
  selector:
    app: comics-server
  ports:
    - port: 80
      targetPort: 4000
  type: ClusterIP