apiVersion: apps/v1
kind: Deployment
metadata:
  name: comics-graphql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: comics-graphql
  template:
    metadata:
      labels:
        app: comics-graphql
    spec:
      containers:
        - name: comics-graphql
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: DATABASE_URL
          imagePullPolicy: Always