apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: v1
kind: Service
metadata:
  name: comics-graphql
  namespace: development
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: comics-graphql
  sessionAffinity: ClientIP
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    keel.sh/policy: glob:dev-*
  name: comics-graphql
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comics-graphql
  template:
    metadata:
      labels:
        app: comics-graphql
      name: comics-graphql
    spec:
      containers:
      - image: damianesteban/comics-graphql:dev-0ca740e
        imagePullPolicy: Always
        name: comics-graphql
        ports:
        - containerPort: 4000
          protocol: TCP