apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: v1
kind: Service
metadata:
  name: comics-graphql
  namespace: production
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: comics-graphql
  sessionAffinity: ClientIP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    keel.sh/policy: all
  name: comics-graphql
  namespace: production
spec:
  replicas: 5
  selector:
    matchLabels:
      app: comics-graphql
  template:
    metadata:
      labels:
        app: comics-graphql
      name: comics-graphql
    spec:
      containers:
      - image: damianesteban/comics-graphql-server:0.1.0
        imagePullPolicy: Always
        name: comics-graphql
        ports:
        - containerPort: 4000
          protocol: TCP