apiVersion: v1
kind: Service
metadata:
  name: comics-graphql
spec:
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comics-graphql
  annotations:
    keel.sh/policy: all
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: comics-graphql
          image: damianesteban/comics-graphql-server:0.1.0